name: Build & Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ğŸ” login to docker hub
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # ğŸ³ build image
      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/logging-demo:latest .

      # ğŸš€ push image
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/logging-demo:latest
